# Generated by Django 3.1.6 on 2021-02-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='IP地址')),
                ('host_name', models.CharField(max_length=255, verbose_name='hostname')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='服务器密码')),
                ('db_port', models.CharField(max_length=255, verbose_name='数据库端口')),
                ('db_usrname', models.CharField(max_length=255, verbose_name='db用户名')),
                ('db_password', models.CharField(max_length=255, verbose_name='db密码')),
                ('db_database', models.CharField(max_length=255, verbose_name='数据库')),
                ('db_schema', models.CharField(max_length=255, verbose_name='数据库模式')),
                ('is_db', models.CharField(default='否', max_length=1, verbose_name='是否数据库服务器')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.CreateModel(
            name='Cron_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('01', 'shell任务'), ('02', 'sql任务')], default='01', max_length=255, verbose_name='任务类型')),
                ('task_connent', models.TextField(blank=True, null=True)),
                ('task_para', models.CharField(max_length=255, verbose_name='任务参数')),
                ('task_sta', models.CharField(default='N', max_length=255, verbose_name='任务状态')),
                ('is_delete', models.CharField(default='N', max_length=255, verbose_name='是否删除')),
                ('exe_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cron_tasks.server_host', verbose_name='执行机器')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
